### ISSUE TITLE
Error building docs

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor-api#19]
I was not able to `nmp run build:docs`. Is there any specific npm version I need?

![image](https://user-images.githubusercontent.com/5677782/137206975-efc0e42b-4c8d-47a8-9f75-49fa9f8191d2.png)

**Comment by LeXXik** [comment]
Hmm, there seems to be a difference when using `yarn` vs `npm` . With NPM I do not get any errors. I am on:

`node v14.16.0`
`npm v6.14.11`

With `npm install` and `npm run build:docs` no errors.
With `yarn install` and `yarn build:docs` there is an error:
![image](https://user-images.githubusercontent.com/5677782/146684978-be245db6-1271-4e7d-8dbb-8de332a93530.png)

Its your call if you want to address it or close.

**Comment by willeastcott** [comment]
We're on the latest version of eslint and that seems to have some strict minimum requirements. You simply have to upgrade node to v14.17.0 or above as the message indicates.
