### ISSUE TITLE
Add Typescript definitions

### ISSUE THREAD

**Issue by querielo** [playcanvas/editor-api#47]
Add into package.json
```
{
    . . .
    "scripts": {
        "build:dts": tsc index.js --outDir types --allowJs --declaration --emitDeclarationOnly
    }
    . . .
}
```

or something like this.

So, `@playcanvas/editor-api` could be used to create a Chrome extension with Typescript. Right now, it's hard to use the repo.

**Comment by willeastcott** [comment]
Hi @querielo - thanks for the suggestion. I have made a quick attempt to add support for generating the TS declarations. Would you be interested to test the generated `.d.ts` file and maybe let me know if it works OK? If it does, I'll do a new release of the NPM package that includes the declarations.

**Comment by willeastcott** [comment]
The only problem I see is:

```
C:\dev\editor-api>npx tsc --pretty false dist\index.d.ts
dist/index.d.ts(547,27): error TS2503: Cannot find namespace 'pc'.
```

If I edit `pc.Entity` to `any`, the types seem to compile ok. For now, I'm not sure what the 'correct' fix is. But yeah, relatively minor problem.

**Comment by querielo** [comment]
@willeastcott  ☝️

**Comment by willeastcott** [comment]
So currently, classes like `ComponentSchema` are exported from the root `index.js`:

https://github.com/playcanvas/editor-api/blob/e169c179ed4bd37e80a286d60bac1598823ac9b7/index.js#L14

But that class (and several others) have the `@category internal` tag in the docs. So presumably, `index.js` can drop all the internal classes. This will prevent `rollup-plugin-dts` from including them in the built `index.d.ts`.

As for the `pc.Entity` problem, actually, it probably does work - I think I just need to compile the types with the PlayCanvas Engine types and presumably `tsc` will find `pc.Entity`.

**Comment by querielo** [comment]
Checked `/** @typedef {import("playcanvas")} pc */` and it also works with `pc.Entity`.

**Comment by querielo** [comment]
@willeastcott

OH. I see. I didn't know that the `api` object in global space of Playcanvas Editor is the `editor` namespace in  **editor-api**
So, **editor-api** should be imported like this:


```js
import { globals as editor } from "@playcanvas/editor-api"
import * as api from "@playcanvas/editor-api"
```

**Comment by willeastcott** [comment]
Hmmm, can we do that in a cleaner, less verbose way I wonder...

**Comment by querielo** [comment]
@willeastcott 

We can try to replace [this line](https://github.com/playcanvas/editor-api/blob/main/rollup.config.mjs#L54) by 

```js
footer: `export as namespace api;
declare global {
    const editor: typeof globals;
}`,
```

Then the library can be imported like this `import "@playcanvas/editor-api";`, and after that there are **api** and **editor** in global space (**api** is a namespace, **editor** is an object). It works for me. But, I am not sure that semantically it is correct.

<img width="509" alt="Screen Shot 2022-10-25 at 02 07 51" src="https://user-images.githubusercontent.com/104348270/197639132-b0f9496a-f42c-4ee4-bc65-6623d627bf26.png">

**Comment by willeastcott** [comment]
So this looks better to me. But if I add that to the `index.d.ts`, can't you still do:

```
import api from "@playcanvas/editor-api"
```

**Comment by willeastcott** [comment]
Just committed this: https://github.com/playcanvas/editor-api/commit/0687f8e138da32f367d0a97e81d8b656c0569a3b
